apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    database: $DB_NAME
    user: grafana_ro
    editable: false
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
